// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PositionDto = {
    /**
     * Longitude coordinate
     */
    lng: number;
    /**
     * Latitude coordinate
     */
    lat: number;
};

export type UserDto = {
    /**
     * User UUID
     */
    id: string;
    /**
     * User name
     */
    name: string;
};

export type MapPositionDto = {
    /**
     * User information
     */
    user: UserDto;
    /**
     * Position coordinates
     */
    position: PositionDto;
};

export type FinishDto = {
    /**
     * User ID
     */
    userId: string;
    /**
     * Finish date and time
     */
    finishedAt: string;
    /**
     * Flyover video generation job ID (if flyover API is configured)
     */
    flyoverJobId?: string;
};

export type FlyoverCallbackDto = {
    /**
     * Flyover job ID
     */
    job_id: string;
    /**
     * Job status
     */
    status: 'completed' | 'failed';
    /**
     * Presigned URL for the generated video
     */
    url?: string;
    /**
     * Error message if the job failed
     */
    error?: string;
};

export type FlyoverStatusDto = {
    /**
     * Flyover video status
     */
    status: 'none' | 'pending' | 'completed' | 'failed';
    /**
     * Presigned URL for the generated video (when status is completed)
     */
    url?: string;
    /**
     * Error message (when status is failed)
     */
    error?: string;
};

export type RankingDto = {
    /**
     * User information
     */
    user: UserDto;
    /**
     * Position coordinates
     */
    position: PositionDto;
    /**
     * Last position coordinates (previous update)
     */
    lastPosition: PositionDto | null;
    /**
     * User status
     */
    status: 'finished' | 'in_progress';
    /**
     * Contest end date (null if not finished)
     */
    endDate: {
        [key: string]: unknown;
    } | null;
    /**
     * Timestamp of last position update
     */
    lastPositionUpdate: string;
    /**
     * Distance in kilometers from the contest target
     */
    distance: number;
    /**
     * Percentage of total distance covered from starting position to target
     */
    progressPercentage: number;
    /**
     * Activity status: FINISHED (race completed), INACTIVE (no position update for 1h), ON_ROAD (moved >100m in last 1h), WAITING (position unchanged)
     */
    activityStatus: 'FINISHED' | 'INACTIVE' | 'ON_ROAD' | 'WAITING';
};

export type PositionHistoryDto = {
    /**
     * User ID
     */
    userId: string;
    /**
     * Contest ID
     */
    contestId: string;
    /**
     * Position coordinates
     */
    position: PositionDto;
    /**
     * Timestamp when position was recorded
     */
    timestamp: string;
};

export type TargetPositionDto = {
    /**
     * Contest name
     */
    name: string;
    /**
     * Longitude coordinate
     */
    lng: number;
    /**
     * Latitude coordinate
     */
    lat: number;
};

export type CurrentContestDto = {
    /**
     * Contest ID/code
     */
    id: string;
    /**
     * Contest name
     */
    name: string;
    /**
     * Maximum number of members allowed in the contest
     */
    members: number;
    /**
     * Contest start date
     */
    dateStart: string;
    /**
     * Contest end date
     */
    dateEnd: string;
    /**
     * Target position coordinates
     */
    targetPosition: TargetPositionDto;
    /**
     * Starting position coordinates
     */
    startingPosition: TargetPositionDto;
    /**
     * Organizer phone number
     */
    organizerPhoneNumber: string;
    /**
     * URL path to contest logo (relative to API root)
     */
    logoUrl: {
        [key: string]: unknown;
    } | null;
};

export type ContestListItemDto = {
    /**
     * Contest ID/code
     */
    id: string;
    /**
     * Contest name
     */
    name: string;
    /**
     * Maximum number of members allowed in the contest
     */
    members: number;
};

export type LogoItemDto = {
    /**
     * Logo filename
     */
    filename: string;
    /**
     * URL path to logo
     */
    url: string;
};

export type PositionInputDto = {
    /**
     * Position name
     */
    name: string;
    /**
     * Latitude
     */
    lat: number;
    /**
     * Longitude
     */
    lng: number;
};

export type CreateContestDto = {
    /**
     * Contest ID (slug)
     */
    id: string;
    /**
     * Contest name
     */
    name: string;
    /**
     * Max members
     */
    members: number;
    /**
     * Start date (ISO 8601)
     */
    dateStart: string;
    /**
     * End date (ISO 8601)
     */
    dateEnd: string;
    /**
     * Starting position
     */
    startingPosition: PositionInputDto;
    /**
     * Target position
     */
    targetPosition: PositionInputDto;
    /**
     * Organizer phone number
     */
    organizerPhoneNumber: string;
};

export type UpdateContestDto = {
    name?: string;
    members?: number;
    dateStart?: string;
    dateEnd?: string;
    startingPosition?: PositionInputDto;
    targetPosition?: PositionInputDto;
    organizerPhoneNumber?: string;
};

export type SetContestLogoDto = {
    /**
     * Logo filename (from /contest/logos list), or null to remove
     */
    logo?: {
        [key: string]: unknown;
    } | null;
};

export type ScheduleEventDto = {
    /**
     * Schedule event ID
     */
    id?: string;
    /**
     * Event start time (ISO 8601)
     */
    time: string;
    /**
     * Event duration in milliseconds (0 = instant)
     */
    duration: number;
    /**
     * Event name
     */
    name: string;
};

export type CreateScheduleEventDto = {
    /**
     * Event time (ISO 8601)
     */
    time: string;
    /**
     * Duration in milliseconds (0 = instant)
     */
    duration: number;
    /**
     * Event name
     */
    name: string;
};

export type UpdateScheduleEventDto = {
    time?: string;
    duration?: number;
    name?: string;
};

export type NewsItemDto = {
    /**
     * News item ID
     */
    id: string;
    /**
     * News title
     */
    title: string;
    /**
     * News description/body
     */
    description: string;
    /**
     * Publication time (ISO 8601)
     */
    time: string;
};

export type CreateNewsDto = {
    /**
     * News title
     */
    title: string;
    /**
     * News description/body
     */
    description: string;
};

export type UpdateNewsDto = {
    /**
     * News title
     */
    title?: string;
    /**
     * News description/body
     */
    description?: string;
};

export type AppControllerGetAuthQrCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User ID (UUID or numeric format)
         */
        userId: string;
        /**
         * User name
         */
        name: string;
    };
    url: '/auth/qr';
};

export type AppControllerGetAuthQrCodeErrors = {
    /**
     * Missing userId or name query parameter
     */
    400: unknown;
};

export type AppControllerGetAuthQrCodeResponses = {
    /**
     * QR code image (PNG)
     */
    200: Blob | File;
};

export type AppControllerGetAuthQrCodeResponse = AppControllerGetAuthQrCodeResponses[keyof AppControllerGetAuthQrCodeResponses];

export type HitchControllerAddPositionData = {
    body: PositionDto;
    headers: {
        /**
         * User authentication (format: Bearer <base64-encoded-userId:contestId>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/map/position';
};

export type HitchControllerAddPositionErrors = {
    /**
     * Invalid position data, user has already finished, contest not started, or contest ended
     */
    400: unknown;
    /**
     * User not authenticated
     */
    403: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerAddPositionResponses = {
    /**
     * Position added successfully
     */
    201: unknown;
};

export type HitchControllerGetMapPositionsAdminData = {
    body?: never;
    headers: {
        /**
         * API Key (format: ApiKey <key>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/map/admin';
};

export type HitchControllerGetMapPositionsAdminErrors = {
    /**
     * Invalid or missing API key
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerGetMapPositionsAdminResponses = {
    /**
     * Map positions with contest start/target info
     */
    200: unknown;
};

export type HitchControllerGetMapPositionsData = {
    body?: never;
    headers: {
        /**
         * User authentication (format: Bearer <base64-encoded-userId:contestId>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/map';
};

export type HitchControllerGetMapPositionsErrors = {
    /**
     * Contest not started or contest ended
     */
    400: unknown;
    /**
     * User not authenticated
     */
    403: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerGetMapPositionsResponses = {
    /**
     * List of all positions
     */
    200: Array<MapPositionDto>;
};

export type HitchControllerGetMapPositionsResponse = HitchControllerGetMapPositionsResponses[keyof HitchControllerGetMapPositionsResponses];

export type HitchControllerFinishContestData = {
    body?: never;
    headers: {
        /**
         * API Key (format: apikey <key>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
        /**
         * User ID
         */
        userId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/finish/{userId}';
};

export type HitchControllerFinishContestErrors = {
    /**
     * User has already finished, contest not started, or contest ended
     */
    400: unknown;
    /**
     * Invalid or missing API key
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerFinishContestResponses = {
    /**
     * Contest finished successfully
     */
    201: FinishDto;
};

export type HitchControllerFinishContestResponse = HitchControllerFinishContestResponses[keyof HitchControllerFinishContestResponses];

export type HitchControllerHandleFlyoverCallbackData = {
    body: FlyoverCallbackDto;
    path: {
        /**
         * Contest ID
         */
        contestId: unknown;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/flyover/callback';
};

export type HitchControllerHandleFlyoverCallbackResponses = {
    /**
     * Callback processed successfully
     */
    201: unknown;
};

export type HitchControllerGetFlyoverStatusData = {
    body?: never;
    path: {
        /**
         * Contest ID
         */
        contestId: string;
        /**
         * User ID
         */
        userId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/flyover/{userId}';
};

export type HitchControllerGetFlyoverStatusResponses = {
    /**
     * Flyover video status
     */
    200: FlyoverStatusDto;
};

export type HitchControllerGetFlyoverStatusResponse = HitchControllerGetFlyoverStatusResponses[keyof HitchControllerGetFlyoverStatusResponses];

export type HitchControllerGetRankingData = {
    body?: never;
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/ranking';
};

export type HitchControllerGetRankingErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerGetRankingResponses = {
    /**
     * List of users ranked by performance
     */
    200: Array<RankingDto>;
};

export type HitchControllerGetRankingResponse = HitchControllerGetRankingResponses[keyof HitchControllerGetRankingResponses];

export type HitchControllerClearContestData = {
    body?: never;
    headers: {
        /**
         * API Key (format: ApiKey <key>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/clear';
};

export type HitchControllerClearContestErrors = {
    /**
     * Invalid or missing API key
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerClearContestResponses = {
    /**
     * Contest data cleared successfully
     */
    200: unknown;
};

export type HitchControllerResetUserData = {
    body?: never;
    headers: {
        /**
         * API Key (format: apikey <key>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
        /**
         * User ID to reset
         */
        userId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/reset/{userId}';
};

export type HitchControllerResetUserErrors = {
    /**
     * Invalid or missing API key
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerResetUserResponses = {
    /**
     * User position and history reset successfully
     */
    200: unknown;
};

export type HitchControllerGetUserHistoryData = {
    body?: never;
    headers: {
        /**
         * User authentication (format: Bearer <base64-encoded-userId:contestId>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/history';
};

export type HitchControllerGetUserHistoryErrors = {
    /**
     * User not authenticated
     */
    403: unknown;
};

export type HitchControllerGetUserHistoryResponses = {
    /**
     * All registered position history points
     */
    200: Array<PositionHistoryDto>;
};

export type HitchControllerGetUserHistoryResponse = HitchControllerGetUserHistoryResponses[keyof HitchControllerGetUserHistoryResponses];

export type HitchControllerGetUserHistoryAdminData = {
    body?: never;
    headers: {
        /**
         * API Key (format: ApiKey <key>)
         */
        Authorization: string;
    };
    path: {
        /**
         * Contest ID
         */
        contestId: string;
        /**
         * User ID
         */
        userId: string;
    };
    query?: never;
    url: '/hitch/contest/{contestId}/history/{userId}';
};

export type HitchControllerGetUserHistoryAdminErrors = {
    /**
     * Invalid or missing API key
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type HitchControllerGetUserHistoryAdminResponses = {
    /**
     * Position history for the user
     */
    200: Array<PositionHistoryDto>;
};

export type HitchControllerGetUserHistoryAdminResponse = HitchControllerGetUserHistoryAdminResponses[keyof HitchControllerGetUserHistoryAdminResponses];

export type ContestControllerGetCurrentContestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contest';
};

export type ContestControllerGetCurrentContestResponses = {
    /**
     * Current contest data
     */
    200: CurrentContestDto;
};

export type ContestControllerGetCurrentContestResponse = ContestControllerGetCurrentContestResponses[keyof ContestControllerGetCurrentContestResponses];

export type ContestControllerCreateContestData = {
    body: CreateContestDto;
    path?: never;
    query?: never;
    url: '/contest';
};

export type ContestControllerCreateContestErrors = {
    /**
     * Contest ID already exists
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ContestControllerCreateContestResponses = {
    /**
     * Contest created
     */
    201: CurrentContestDto;
};

export type ContestControllerCreateContestResponse = ContestControllerCreateContestResponses[keyof ContestControllerCreateContestResponses];

export type ContestControllerGetContestListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contest/list';
};

export type ContestControllerGetContestListResponses = {
    /**
     * List of contests with ID and name
     */
    200: Array<ContestListItemDto>;
};

export type ContestControllerGetContestListResponse = ContestControllerGetContestListResponses[keyof ContestControllerGetContestListResponses];

export type ContestControllerGetLogosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contest/logos';
};

export type ContestControllerGetLogosResponses = {
    /**
     * Available logo files served from /resources/
     */
    200: Array<LogoItemDto>;
};

export type ContestControllerGetLogosResponse = ContestControllerGetLogosResponses[keyof ContestControllerGetLogosResponses];

export type ContestControllerDeleteContestData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}';
};

export type ContestControllerDeleteContestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerDeleteContestResponses = {
    /**
     * Contest deleted
     */
    200: unknown;
};

export type ContestControllerGetContestByIdData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}';
};

export type ContestControllerGetContestByIdErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerGetContestByIdResponses = {
    /**
     * Contest data
     */
    200: CurrentContestDto;
};

export type ContestControllerGetContestByIdResponse = ContestControllerGetContestByIdResponses[keyof ContestControllerGetContestByIdResponses];

export type ContestControllerUpdateContestData = {
    body: UpdateContestDto;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}';
};

export type ContestControllerUpdateContestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerUpdateContestResponses = {
    /**
     * Contest updated
     */
    200: CurrentContestDto;
};

export type ContestControllerUpdateContestResponse = ContestControllerUpdateContestResponses[keyof ContestControllerUpdateContestResponses];

export type ContestControllerSetContestLogoData = {
    body: SetContestLogoDto;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/logo';
};

export type ContestControllerSetContestLogoErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerSetContestLogoResponses = {
    /**
     * Contest logo updated
     */
    200: CurrentContestDto;
};

export type ContestControllerSetContestLogoResponse = ContestControllerSetContestLogoResponses[keyof ContestControllerSetContestLogoResponses];

export type ContestControllerGetScheduleData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/schedule';
};

export type ContestControllerGetScheduleErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerGetScheduleResponses = {
    /**
     * Schedule events grouped by day (UTC midnight ISO string as key)
     */
    200: unknown;
};

export type ContestControllerAddScheduleEventData = {
    body: CreateScheduleEventDto;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/schedule';
};

export type ContestControllerAddScheduleEventErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerAddScheduleEventResponses = {
    /**
     * Schedule event created
     */
    201: ScheduleEventDto;
};

export type ContestControllerAddScheduleEventResponse = ContestControllerAddScheduleEventResponses[keyof ContestControllerAddScheduleEventResponses];

export type ContestControllerGetScheduleEventsData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/schedule/list';
};

export type ContestControllerGetScheduleEventsErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerGetScheduleEventsResponses = {
    /**
     * List of schedule events
     */
    200: Array<ScheduleEventDto>;
};

export type ContestControllerGetScheduleEventsResponse = ContestControllerGetScheduleEventsResponses[keyof ContestControllerGetScheduleEventsResponses];

export type ContestControllerDeleteScheduleEventData = {
    body?: never;
    path: {
        contestId: string;
        eventId: string;
    };
    query?: never;
    url: '/contest/{contestId}/schedule/{eventId}';
};

export type ContestControllerDeleteScheduleEventErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest or event not found
     */
    404: unknown;
};

export type ContestControllerDeleteScheduleEventResponses = {
    /**
     * Schedule event deleted
     */
    200: unknown;
};

export type ContestControllerUpdateScheduleEventData = {
    body: UpdateScheduleEventDto;
    path: {
        contestId: string;
        eventId: string;
    };
    query?: never;
    url: '/contest/{contestId}/schedule/{eventId}';
};

export type ContestControllerUpdateScheduleEventErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest or event not found
     */
    404: unknown;
};

export type ContestControllerUpdateScheduleEventResponses = {
    /**
     * Schedule event updated
     */
    200: ScheduleEventDto;
};

export type ContestControllerUpdateScheduleEventResponse = ContestControllerUpdateScheduleEventResponses[keyof ContestControllerUpdateScheduleEventResponses];

export type ContestControllerGetRankingData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/ranking';
};

export type ContestControllerGetRankingErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerGetRankingResponses = {
    /**
     * Contest ranking with users and their locations
     */
    200: Array<RankingDto>;
};

export type ContestControllerGetRankingResponse = ContestControllerGetRankingResponses[keyof ContestControllerGetRankingResponses];

export type ContestControllerAddParticipantData = {
    body: {
        userId: string;
        name: string;
    };
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/participants';
};

export type ContestControllerAddParticipantErrors = {
    /**
     * User already registered or contest is full
     */
    400: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerAddParticipantResponses = {
    /**
     * Participant added successfully
     */
    201: unknown;
};

export type ContestControllerPopulateUserNamesData = {
    /**
     * Mapping of user IDs to names
     */
    body: {
        [key: string]: string;
    };
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/populate';
};

export type ContestControllerPopulateUserNamesErrors = {
    /**
     * Invalid user ID or contest not found
     */
    400: unknown;
};

export type ContestControllerPopulateUserNamesResponses = {
    /**
     * User names populated successfully
     */
    200: unknown;
};

export type ContestControllerPrepopulateRandomlyData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/prepopulate-randomly';
};

export type ContestControllerPrepopulateRandomlyErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerPrepopulateRandomlyResponses = {
    /**
     * Contest prepopulated with random data
     */
    200: unknown;
};

export type ContestControllerGetNewsData = {
    body?: never;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/news';
};

export type ContestControllerGetNewsErrors = {
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerGetNewsResponses = {
    /**
     * List of news items sorted by time (newest first)
     */
    200: Array<NewsItemDto>;
};

export type ContestControllerGetNewsResponse = ContestControllerGetNewsResponses[keyof ContestControllerGetNewsResponses];

export type ContestControllerAddNewsData = {
    body: CreateNewsDto;
    path: {
        contestId: string;
    };
    query?: never;
    url: '/contest/{contestId}/news';
};

export type ContestControllerAddNewsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest not found
     */
    404: unknown;
};

export type ContestControllerAddNewsResponses = {
    /**
     * News item created
     */
    201: NewsItemDto;
};

export type ContestControllerAddNewsResponse = ContestControllerAddNewsResponses[keyof ContestControllerAddNewsResponses];

export type ContestControllerDeleteNewsData = {
    body?: never;
    path: {
        contestId: string;
        newsId: string;
    };
    query?: never;
    url: '/contest/{contestId}/news/{newsId}';
};

export type ContestControllerDeleteNewsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest or news item not found
     */
    404: unknown;
};

export type ContestControllerDeleteNewsResponses = {
    /**
     * News item deleted
     */
    200: unknown;
};

export type ContestControllerUpdateNewsData = {
    body: UpdateNewsDto;
    path: {
        contestId: string;
        newsId: string;
    };
    query?: never;
    url: '/contest/{contestId}/news/{newsId}';
};

export type ContestControllerUpdateNewsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Contest or news item not found
     */
    404: unknown;
};

export type ContestControllerUpdateNewsResponses = {
    /**
     * News item updated
     */
    200: NewsItemDto;
};

export type ContestControllerUpdateNewsResponse = ContestControllerUpdateNewsResponses[keyof ContestControllerUpdateNewsResponses];

export type ContestControllerGetContestQrData = {
    body?: never;
    path: {
        contestId: string;
    };
    query: {
        userId: string;
    };
    url: '/contest/{contestId}/qr';
};

export type ContestControllerGetContestQrResponses = {
    /**
     * QR code image
     */
    200: Blob | File;
};

export type ContestControllerGetContestQrResponse = ContestControllerGetContestQrResponses[keyof ContestControllerGetContestQrResponses];
